# Deps

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.0.17"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"
